### ISSUE TITLE
请问这个opencmdb项目的发布时间

### ISSUE THREAD

**Issue by xiaohuazi123** [unixhot/opencmdb-docs#2]
这个opencmdb项目 就是 赵大神你的说今年下半年 会出的，django+vuejs+saltstack的项目吗？
顺便集成堡垒机？

**Comment by unixhot** [comment]
不是的，那个项目早就废弃了，新的功能很完整，年底开源，先推出免费版本发自我的iPhone------------------ 原始邮件 ------------------发件人: steven  <notifications@github.com>发送时间: 2020年3月14日 21:11收件人: unixhot/opencmdb-docs <opencmdb-docs@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[unixhot/opencmdb-docs] 请问这个opencmdb项目的发布时间 (#2)
这个opencmdb项目 就是 赵大神你的说今年下半年 会出的，django+vuejs+saltstack的项目吗？
顺便集成堡垒机？

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/unixhot/opencmdb-docs/issues/2",
"url": "https://github.com/unixhot/opencmdb-docs/issues/2",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by xiaohuazi123** [comment]
好的，期待
